In [58]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [59]:
#!pip install autopep8


In [60]:
import statsmodels.api as sm
from sklearn.model_selection import KFold 


In [61]:
from function_library import *



In [62]:
df_kc = load_kc_data(filename='kc_house_data.csv', verbose=False)



In [63]:
kf = KFold(n_splits=10, random_state=42, shuffle=True) # Define the split - into 10 folds 
kf.get_n_splits(df_kc) # returns the number of splitting iterations in the cross-validator
#print(kf) 
# https://stackoverflow.com/questions/45115964/separate-pandas-dataframe-using-sklearns-kfold

train_list=[]
test_list=[]
for train_index, test_index in kf.split(df_kc): 
    test_list.append(df_kc.iloc[train_index])
    train_list.append(df_kc.iloc[train_index])
    print(test_index)
    
#     locals()['df{0}_train'.format(i)] = df.iloc[train_index]
#     locals()['df{0}_test'.format(i)] = df.iloc[test_index]
    

    


[   34    44    54 ... 21555 21559 21569]
[    3     6    17 ... 21586 21591 21595]
[    0    19    29 ... 21566 21583 21585]
[    5     8    14 ... 21561 21567 21592]
[    7    15    23 ... 21550 21558 21572]
[    2    10    22 ... 21587 21589 21590]
[   12    21    28 ... 21524 21527 21576]
[    1     4    18 ... 21574 21580 21593]
[   16    24    25 ... 21557 21578 21588]
[    9    11    13 ... 21582 21594 21596]


In [64]:
type(X)

pandas.core.frame.DataFrame

In [65]:
X.shape

(19437, 12)

In [66]:
shape

NameError: name 'shape' is not defined

In [67]:
y.shape

(19437,)

In [68]:
type(y)

pandas.core.series.Series

In [69]:
type(model)

statsmodels.regression.linear_model.RegressionResultsWrapper

In [70]:
X.dtypes

bedrooms                  int64
bathrooms               float64
sqft_living               int64
sqft_lot                  int64
waterfront              float64
grade                     int64
sqft_above                int64
yr_built                  int64
sqft_living15             int64
sqft_lot15                int64
time_since_renovated    float64
zipcode_rank              int64
dtype: object

In [82]:
model_summary_list=[0]*10
for i in range(10):
    df = train_list[i]
    df = replace_with_year(df, 'date')
    #df = drop_columns(df, ["id"])
    df = fill_na_with_median(df, 'waterfront')
    df = fill_na_with_median(df, 'view')
    df = fill_na_with_median(df, 'yr_renovated')
    df = replace_values_with_another_column(df, [0], "yr_renovated", "yr_built", replace_na=True)
    df = add_time_since_renovated_feature(df, 'date', 'yr_renovated')
    df = add_zipcode_ranking_feature(df, 'zipcode', 'price')
    df.drop('sqft_basement', axis=1)

    X = train_list[i].drop(['id','date','sqft_basement','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    X_test = test_list[i].drop(['id','date','sqft_basement','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    y = train_list[i].price
    
    model = sm.OLS(y, X).fit()
    predictions_train = model.predict(X)
   # predictions_test = model.predict(X_test)
    model_summary_list[i]=model.summary()
    
    
    print('The R squared of the model generated from the training data is: ')
    print(model.rsquared)
    print('The square root of the mean squared error for the training data is: ')
    print(np.sqrt(np.mean((predictions_train-y)**2)))
    print(' ')

/Users/josephdown/mod1-project/function_library.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[columns] = functions(df[columns])
/Users/josephdown/mod1-project/function_library.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[column] = df[column].map(lambda x: x.year)
/Users/josephdown/mod1-project/function_library.py:548: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pyda

The R squared of the model generated from the training data is: 
0.9073435198602059
The square root of the mean squared error for the training data is: 
199514.5478363773
 
The R squared of the model generated from the training data is: 
0.9084092005408801
The square root of the mean squared error for the training data is: 
197612.2995607449
 
The R squared of the model generated from the training data is: 
0.9085911686568908
The square root of the mean squared error for the training data is: 
197539.51140346003
 
The R squared of the model generated from the training data is: 
0.9095720998805068
The square root of the mean squared error for the training data is: 
195581.07441388787
 
The R squared of the model generated from the training data is: 
0.9068365896223525
The square root of the mean squared error for the training data is: 
199518.48082310727
 
The R squared of the model generated from the training data is: 
0.9083210300809648
The square root of the mean squared error for th

In [85]:
model_summary_list=[0]*10
for i in range(10):
    df = train_list[i]
    df = replace_with_year(df, 'date')
    #df = drop_columns(df, ["id"])
    df = fill_na_with_median(df, 'waterfront')
    df = fill_na_with_median(df, 'view')
    df = fill_na_with_median(df, 'yr_renovated')
    df = replace_values_with_another_column(df, [0], "yr_renovated", "yr_built", replace_na=True)
    df = add_time_since_renovated_feature(df, 'date', 'yr_renovated')
    df = add_zipcode_ranking_feature(df, 'zipcode', 'price')
    df.drop('sqft_basement', axis=1)
    #df = replace_values_with_value(df, '?', 'sqft_basement', '0.0')
    #df = convert_columns_with_function(df, "sqft_basement", pd.to_numeric)
    
    df_test = test_list[i]
    df_test = replace_with_year(df, 'date')
    #df = drop_columns(df, ["id"])
    df_test = fill_na_with_median(df, 'waterfront')
    df_test = fill_na_with_median(df, 'view')
    df_test = fill_na_with_median(df, 'yr_renovated')
    df_test = replace_values_with_another_column(df, [0], "yr_renovated", "yr_built", replace_na=True)
    df_test = add_time_since_renovated_feature(df, 'date', 'yr_renovated')
    df_test = add_zipcode_ranking_feature(df, 'zipcode', 'price')
    df_test.drop('sqft_basement', axis=1)
    #df = replace_values_with_value(df, '?', 'sqft_basement', '0.0')
    #df = convert_columns_with_function(df, "sqft_basement", pd.to_numeric)

    X = df.drop(['id','date','sqft_basement','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    X_test = df_test.drop(['id','date','sqft_basement','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    y = df.price
    
    model = sm.OLS(y, X).fit()
    predictions_train = model.predict(X)
    predictions_test = model.predict(X_test)
    model_summary_list[i]=model.summary()
    
    print('The R squared of the model generated from the training data is: ')
    print(model.rsquared)
    print('The square root of the mean squared error for the training data is: ')
    print(np.sqrt(np.mean((predictions_train-y)**2)))
    print('The square root of the mean squared error predicted from the testing data is: ')
    print(np.sqrt(np.mean((predictions_train-y)**2)))
    print(' ')

/Users/josephdown/mod1-project/function_library.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[columns] = functions(df[columns])
/Users/josephdown/mod1-project/function_library.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[column] = df[column].map(lambda x: x.year)
/Users/josephdown/mod1-project/function_library.py:548: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pyda

The R squared of the model generated from the training data is: 
0.9073435198602059
The square root of the mean squared error for the training data is: 
199514.5478363773
The square root of the mean squared error predicted from the testing data is: 
199514.5478363773
 
The R squared of the model generated from the training data is: 
0.9084092005408801
The square root of the mean squared error for the training data is: 
197612.2995607449
The square root of the mean squared error predicted from the testing data is: 
197612.2995607449
 
The R squared of the model generated from the training data is: 
0.9085911686568908
The square root of the mean squared error for the training data is: 
197539.51140346003
The square root of the mean squared error predicted from the testing data is: 
197539.51140346003
 
The R squared of the model generated from the training data is: 
0.9095720998805068
The square root of the mean squared error for the training data is: 
195581.07441388787
The square root 

In [ ]:
df.columns




In [ ]:
from function_library import *

In [ ]:
model_summary_list=[0]*10
for i in range(10):
    df = train_list[i]
    df = replace_with_year(df, 'date')
    #df = drop_columns(df, ["id"])
    df = fill_na_with_median(df, 'waterfront')
    df = fill_na_with_median(df, 'view')
    df = fill_na_with_median(df, 'yr_renovated')
    df = replace_values_with_another_column(df, [0], "yr_renovated", "yr_built", replace_na=True)
    df = convert_float_to_datetime(df, 'yr_renovated')
    df = date_to_date_time(df, 'date')
    df = time_since_rennovated_added_in_days(df, 'date', 'yr_renovated')
    #df = add_time_since_renovated_feature(df, 'date', 'yr_renovated')
    df = add_zipcode_ranking_feature(df, 'zipcode', 'price')
    df.drop('sqft_basement', axis=1)
    #df = replace_values_with_value(df, '?', 'sqft_basement', '0.0')
    #df = convert_columns_with_function(df, "sqft_basement", pd.to_numeric)

    X = train_list[i].drop(['id','date','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    X_test = test_list[i].drop(['id','date','price','view','floors','condition','yr_renovated','zipcode','lat','long'],axis=1)
    y = train_list[i].price
    #need to add a constant value?  See example below
    model = sm.OLS(y, X).fit()
    predictions_train = model.predict(X)
    predictions_test = model.predict(X_test)
    model_summary_list[i]=model.summary()
    print(model.rsquared)

In [ ]:
df_kc.head()

In [80]:
X.shape




(19438, 12)

In [81]:
X_test.shape

(19438, 10)